### ISSUE TITLE
Naar github verwijzen in verslag

### ISSUE THREAD

**Issue by MerelEussen** [tueimage/crowd-airway-bsc-2018#10]
De laatste versie van alle bestanden heb ik naar github gepusht. Nu wilde ik iets over github toevoegen aan het verslag, maar ik bedenk mij net dat dit een prive pagina is. Is het dan niet raar als ik een link of screenshot toevoeg, terwijl dit niet voor iedereen toegankelijk is?

**Comment by vcheplygina** [comment]
Dat ging zonder problemen, dus nu is master up to date. Je kunt evt daar de laatste wijzigingen doen (maar normaal gesproken zou dat in bep2018 zijn, en dan weer mergen)
